# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10147fb384e87204f716eb791b90576cd8dc751b39713f22faea69b913f18c8d84b049d116e8bb1dd82ada23619533de3bb2a3c628d8ce453c23fd628eb245a

test:
  secret_key_base: 609cb31cfededcbd9881e09fd55c6ad55468e890478091d9e48851b911927807f0355d60308bc97bccc741995c86527fffbbc3aae6c3816d32ffb429e8e50603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
